export const WEEKDAY_NAMES={1:'一',2:'二',3:'三',4:'四',5:'五',6:'六',7:'日'};
export const blankRule=()=>({type:'daily',mode:'daily',count:1,weekdays:[],weekNumbers:[],monthDates:[],monthWeeks:[],months:[],quarters:[],quarterMonths:[],quarterDates:[],yearWeeks:[],yearDates:[],intervalDays:1,startDate:'',fallbackToLastDay:true});
export function ruleFromLegacy(frequency){const r=blankRule();if(!frequency||frequency==='daily')return r;if(frequency==='weekly')return {...r,type:'weekly',mode:'count',count:1,intervalDays:7};if(frequency==='flex')return {...r,type:'weekly',mode:'count',count:1,intervalDays:7};return r}
export function normalizeRule(rule, legacy){const r={...blankRule(),...(rule||{})};if(!rule&&legacy)return ruleFromLegacy(legacy);r.count=Number(r.count)||1;r.intervalDays=Number(r.intervalDays)||({daily:1,weekly:7,tenDays:10,biweekly:14,monthly:30,quarterly:90,yearly:365}[r.type]||1);['weekdays','weekNumbers','monthDates','monthWeeks','months','quarters','quarterMonths','yearWeeks'].forEach(k=>{r[k]=Array.isArray(r[k])?r[k].map(v=>v==='last'?'last':Number(v)).filter(v=>v==='last'||!Number.isNaN(v)):[]});r.quarterDates=Array.isArray(r.quarterDates)?r.quarterDates.map(x=>({month:Number(x.month)||1,date:x.date==='last'?'last':Number(x.date)||1})):[];r.yearDates=Array.isArray(r.yearDates)?r.yearDates.map(x=>({month:Number(x.month)||1,date:x.date==='last'?'last':Number(x.date)||1})):[];r.startDate=r.startDate||'';r.fallbackToLastDay=r.fallbackToLastDay!==false;return r}
function pad(n){return String(n).padStart(2,'0')}export function dateKey(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function startOfDay(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}function wd(d){const x=d.getDay();return x===0?7:x}function daysInMonth(y,m){return new Date(y,m,0).getDate()}function isLastDay(d){return d.getDate()===daysInMonth(d.getFullYear(),d.getMonth()+1)}function isDateMatch(d,dates){const day=d.getDate();return dates.some(x=>x==='last'?isLastDay(d):Number(x)===day)}function weekOfMonth(d){return Math.ceil(d.getDate()/7)}function isLastWeekOfMonth(d){const next=new Date(d);next.setDate(d.getDate()+7);return next.getMonth()!==d.getMonth()}function weekMatch(d,weeks){const w=weekOfMonth(d);return weeks.some(x=>x==='last'?isLastWeekOfMonth(d):Number(x)===w)}
export function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const yearStart=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-yearStart)/86400000)+1)/7)}
function quarter(d){return Math.floor(d.getMonth()/3)+1}function quarterMonth(d){return d.getMonth()%3+1}function diffDays(a,b){return Math.floor((Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())-Date.UTC(b.getFullYear(),b.getMonth(),b.getDate()))/86400000)}function startDate(r){return r.startDate?new Date(r.startDate+'T00:00:00'):new Date('2026-01-01T00:00:00')}
export function isCountMode(r){r=normalizeRule(r);return ['count','weeklyCount','tenDaysCount','biweeklyCount','monthlyCount','quarterlyCount','yearlyCount'].includes(r.mode)}
export function periodStart(rule,date=new Date()){const r=normalizeRule(rule);const d=startOfDay(date);if(r.type==='daily')return d;if(r.type==='weekly'){const x=new Date(d);x.setDate(d.getDate()-wd(d)+1);return x}if(r.type==='tenDays'){const s=startDate(r);const n=Math.floor(diffDays(d,s)/10);return addDays(s,n*10)}if(r.type==='biweekly'){const s=startDate(r);const n=Math.floor(diffDays(d,s)/14);return addDays(s,n*14)}if(r.type==='monthly')return new Date(d.getFullYear(),d.getMonth(),1);if(r.type==='quarterly')return new Date(d.getFullYear(),Math.floor(d.getMonth()/3)*3,1);if(r.type==='yearly')return new Date(d.getFullYear(),0,1);return d}
export function periodEnd(rule,date=new Date()){const r=normalizeRule(rule);const s=periodStart(r,date);if(r.type==='daily')return addDays(s,1);if(r.type==='weekly')return addDays(s,7);if(r.type==='tenDays')return addDays(s,10);if(r.type==='biweekly')return addDays(s,14);if(r.type==='monthly')return new Date(s.getFullYear(),s.getMonth()+1,1);if(r.type==='quarterly')return new Date(s.getFullYear(),s.getMonth()+3,1);if(r.type==='yearly')return new Date(s.getFullYear()+1,0,1);return addDays(s,1)}
export function periodKey(rule,date=new Date()){const r=normalizeRule(rule);const s=periodStart(r,date);if(r.type==='daily')return `daily:${dateKey(s)}`;if(r.type==='weekly')return `weekly:${s.getFullYear()}:W${isoWeek(s)}`;if(r.type==='tenDays')return `tenDays:${dateKey(s)}`;if(r.type==='biweekly')return `biweekly:${dateKey(s)}`;if(r.type==='monthly')return `monthly:${s.getFullYear()}-${pad(s.getMonth()+1)}`;if(r.type==='quarterly')return `quarterly:${s.getFullYear()}-Q${quarter(s)}`;if(r.type==='yearly')return `yearly:${s.getFullYear()}`;return `daily:${dateKey(s)}`}
export function periodMeta(rule,date=new Date()){const r=normalizeRule(rule);const s=periodStart(r,date);const e=periodEnd(r,date);return {periodKey:periodKey(r,date),periodStart:dateKey(s),periodEnd:dateKey(addDays(e,-1)),nextPeriodStart:dateKey(e),type:r.type,count:r.count}}
export function periodLabel(rule,date=new Date()){const r=normalizeRule(rule);if(r.type==='weekly')return `本週`;if(r.type==='tenDays')return `本 10 天`;if(r.type==='biweekly')return `本雙週`;if(r.type==='monthly')return `本月`;if(r.type==='quarterly')return `本季`;if(r.type==='yearly')return `本年`;return '今日'}
export function isDueToday(rule,date=new Date()){const r=normalizeRule(rule);if(isCountMode(r))return false;if(r.type==='daily')return true;if(r.type==='weekly')return r.weekdays.includes(wd(date));if(r.type==='tenDays'){const n=((diffDays(date,startDate(r))%10)+10)%10+1;return r.monthDates.includes(n)}if(r.type==='biweekly'){const day=diffDays(date,startDate(r));const week=Math.floor((((day%14)+14)%14)/7)+1;return r.weekNumbers.includes(week)&&r.weekdays.includes(wd(date))}if(r.type==='monthly'){if(r.mode==='monthDates')return isDateMatch(date,r.monthDates);if(r.mode==='monthWeeks')return weekMatch(date,r.monthWeeks)&&r.weekdays.includes(wd(date));}if(r.type==='quarterly'){if(r.mode==='quarterMonths')return r.quarterMonths.includes(quarterMonth(date));if(r.mode==='quarterDates')return r.quarterDates.some(x=>x.month===quarterMonth(date)&&(x.date==='last'?isLastDay(date):x.date===date.getDate()));}if(r.type==='yearly'){if(r.mode==='yearQuarters')return r.quarters.includes(quarter(date));if(r.mode==='yearMonths')return r.months.includes(date.getMonth()+1);if(r.mode==='yearDates')return r.yearDates.some(x=>x.month===date.getMonth()+1&&(x.date==='last'?isLastDay(date):x.date===date.getDate()));if(r.mode==='yearWeeks')return r.yearWeeks.includes(isoWeek(date))&&r.weekdays.includes(wd(date));}return false}
export function frequencyDescription(rule){const r=normalizeRule(rule);const wds=r.weekdays.map(x=>'週'+WEEKDAY_NAMES[x]).join('、');const nums=a=>a.map(x=>x==='last'?'月底':x).join('、');const weeks=a=>a.map(x=>x==='last'?'最後一週':`第 ${x} 週`).join('、');if(r.type==='daily')return '每日';if(r.type==='weekly')return isCountMode(r)?`每週 ${r.count} 次`:`每${wds}`;if(r.type==='tenDays')return isCountMode(r)?`每 10 天 ${r.count} 次`:`每 10 天第 ${nums(r.monthDates)} 天`;if(r.type==='biweekly')return isCountMode(r)?`每雙週 ${r.count} 次`:`每雙週${weeks(r.weekNumbers)} ${wds}`;if(r.type==='monthly'){if(isCountMode(r))return `每月 ${r.count} 次`;if(r.mode==='monthDates')return `每月 ${nums(r.monthDates)}`;return `每月${weeks(r.monthWeeks)} ${wds}`}if(r.type==='quarterly'){if(isCountMode(r))return `每季 ${r.count} 次`;if(r.mode==='quarterMonths')return `每季第 ${nums(r.quarterMonths)} 個月`;return `每季${r.quarterDates.map(x=>`第 ${x.month} 個月 ${x.date==='last'?'月底':x.date+' 號'}`).join('、')}`}if(r.type==='yearly'){if(isCountMode(r))return `每年 ${r.count} 次`;if(r.mode==='yearQuarters')return `每年第 ${nums(r.quarters)} 季`;if(r.mode==='yearMonths')return `每年 ${nums(r.months)} 月`;if(r.mode==='yearDates')return `每年 ${r.yearDates.map(x=>`${x.month}/${x.date==='last'?'月底':x.date}`).join('、')}`;return `每年第 ${nums(r.yearWeeks)} 週 ${wds}`}return '每日'}
